version: "3.9"
name: "tcc"

services:
  redis:
    image: redis:7.4.2
    container_name: redis_tcc
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - tcc_network

volumes:
  redis_data:

networks:
  tcc_network:
    driver: bridge
