name: "tcc"

services:
  redis:
    image: redis:7.4.2
    container_name: redis_tcc
    restart: always
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "no", "--save", ""]
    networks:
      - tcc_network

networks:
  tcc_network:
    driver: bridge
